spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.219.4/finanuce?useUnicode=true&characterEncoding=utf8&SSL=false
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  mail:
    host: smtp.qq.com
    username: 792053282@qq.com
    password: rsoouzymgqvlbajp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  type-aliases-package: com.qf.domain
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8082



